# Generated by Django 6.0.1 on 2026-01-24 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.PositiveIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
            options={
                'ordering': ['stop_number'],
                'unique_together': {('train', 'station')},
            },
        ),
    ]
