# Generated by Django 6.0.1 on 2026-01-24 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trainroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
            options={
                'unique_together': {('train', 'travel_date')},
            },
        ),
    ]
