# Generated by Django 6.0.1 on 2026-01-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats_booked',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
