# Generated by Django 6.0.1 on 2026-01-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_seats_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats_booked',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLIST', 'Waitlist'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
